# embedding name
LM_NAME_FASTTEXT="fasttext"
LM_NAME_BERT_BASE_UNCASED='bert-base-uncased'

# debug level
LOGGING_LEVEL_CRITICAL="CRITICAL"
LOGGING_LEVEL_ERROR="ERROR"
LOGGING_LEVEL_WARNING="WARNING"
LOGGING_LEVEL_INFO="INFO"
LOGGING_LEVEL_DEBUG="DEBUG"
LOGGING_LEVEL_NOTSET="NOTSET"

# dir and file name
FILE_NAME_DATASET = "dataset.json"

# meta-task information
META_TASK_GLB_LABID            = "META_TASK_GLB_LABID"
META_TASK_SHOT_GLB_LABID       = "META_TASK_SHOT_GLB_LABID"
META_TASK_SHOT_LOC_LABID       = "META_TASK_SHOT_LOC_LABID"
META_TASK_SHOT_DATAIND         = "META_TASK_SHOT_DATAIND"
META_TASK_SHOT_TOKEN           = "META_TASK_SHOT_TOKEN"
META_TASK_SHOT_LAB             = "META_TASK_SHOT_LAB"
META_TASK_QUERY_GLB_LABID      = "META_TASK_QUERY_GLB_LABID"
META_TASK_QUERY_LOC_LABID      = "META_TASK_QUERY_LOC_LABID"
META_TASK_QUERY_DATAIND        = "META_TASK_QUERY_DATAIND"
META_TASK_QUERY_TOKEN          = "META_TASK_QUERY_TOKEN"
META_TASK_QUERY_LAB            = "META_TASK_QUERY_LAB"

# classifier name for validation and evaluation, meta-evaluation
CLSFIER_LINEAR_REGRESSION = "Linear"
CLSFIER_SVM               = "SVM"
CLSFIER_NN                = "NN"
CLSFIER_COSINE            = "Cosine"
CLSFIER_MULTI_LABEL        = "MultiLabel"

# optmizer name
OPTER_ADAM = "Adam"
OPTER_SGD  = "SGD"

# path
SAVE_PATH = './saved_models'
DATA_PATH = './data'